### ISSUE TITLE
Current example configuration will transform anonaddy in openrelay on hosts with ipv6

### ISSUE THREAD

**Issue by slurdge** [anonaddy/docker#205]
After struggling for a while with https://github.com/anonaddy/anonaddy/issues/443 , I found that if you have a host with ipv6, _but not configured in docker_, then the current examples configuration will transform anonaddy in open relay.
What happens:

 - External connection is made with ipv6 on port 25 (on which docker listens to).
 - There no ipv6 for the internal image, so docker does address translation (a bit like NAT) and rewrite the source address as a local one
 - The configuration takes local address as trusted, and does not verify the destination

I think it's normal behaviour for Postfix to trust local addresses, as this is how it communicates with Anonaddy.
However I believe it would be best to:

 - Put a warning in the documentation/examples about this problem
 - Change the examples to listen to `0.0.0.0:25` instead of `25`. People who have a real ipv6 for their containers would be able to adapt quite easily the configuration.

**Comment by yurividal** [comment]
Thats a very good insight. I chgecked my VPS and indeed it was open for ipv6 on 25.
Just changed my docker-compose.

**Comment by crazy-max** [comment]
@slurdge Thanks for your feedback, that's a good point. What's your `/etc/docker/daemon.json` config and also output of `docker info` please.

**Comment by crazy-max** [comment]
Ok so experimental ipv6 is not enabled in your dockerd config.

I was looking at other dockerized mail apps and found this issue https://github.com/mailcow/mailcow-dockerized/issues/4220. Looks like this was an issue with docker compose but you should not be impacted with `2.17.2`.

Also found https://mailu.io/2.0/faq.html#how-to-make-ipv6-work which also says to disable `userland-proxy` when enabling ipv6 (with dockerd experimental ipv6 or through `docker-ipv6nat` container). But again you don't have any of those set up on your side so I still wonder how you could be impacted.

Does setting `enable_ipv6: false` in your compose file works?

**Comment by slurdge** [comment]
I think my issue is more related to https://github.com/docker-mailserver/docker-mailserver/issues/1405
Basically, from my understanding, if you take default docker & docker compose config, _and if you are on an ipv6_ host, if you listen to a port then docker will listen on both ipv4 and ipv6 for the same port, but will rewrite the ipv6 packet to an ipv4 packet with a private address.

I believe this happens whether you enable ipv6 or not.
To prove it, you can try the following command in an ipv6 capable host:
```bash
docker run -it -p 3000:3000 --rm bash:4.4 -c "nc -vvl 3000"
```
and you will see that docker is indeed listening on `::3000`

So I can try to put `enable_ipv6: false` in my compose instead of having the bind to the ipv4, to see if it has the same effect.

**Comment by polarathene** [comment]
Ello, I just responded to a recent comment on the referenced issue: https://github.com/docker-mailserver/docker-mailserver/issues/1405#issuecomment-1539254443

If you allow IPv6 connections from your host, then disabling `userland-proxy` should prevent the problem as advised earlier. There's a few other behaviours that change there that I'm aware of which might affect you if your containers try to interact with other containers indirectly through the host IP.

Alternatively, just configure a IPv6 ULA network. This is similar to IPv4 private networks that docker creates for you and will enable IPv6 on those networks with containers getting their own private IPv6 address assigned. This will now be an IPv6 gateway IP instead, if you need that to match the remote client IPv6 address, then you need to enable the daemon setting `ip6tables: true`, which currently still requires `experimental: true` as well.

Finally for your network, if it's created via the compose config, use `enable_ipv6: true` (_and define an IPv6 ULA subnet like `fd00:feed:face:f00d::/64`_), otherwise when you create the network with `docker network create` include the `--ipv6` + `--subnet fd00:feed:face:f00d::/64` option.

Be sure to run `systemctl daemon-reload && systemctl restart docker` after updating `/etc/docker/daemon.json`. And for docker compose, force-recreate containers may be necessary (_`docker compose down && docker compose up -d` or `docker compose up -d --force-recreate`_). When a client connects over IPv6 now, their IP should persist into the container instead of being replaced with the docker gateway IP.

**Comment by crazy-max** [comment]
@polarathene Thanks for your feedback! Closing since this should be addressed in your environment.
