### ISSUE TITLE
Add support for binding docker ports to 'localhost'

### ISSUE THREAD

**Issue by Flunkyball** [anonaddy/docker#36]
The current setup automatically binds port 25 for postfix and 8000 for the webapp to the hosts external IP address.
However, in my scenario I want only port 25 to bind directly to the hosts IP whereas the webapp should be available only on localhost in order to expose it through an additional reverse proxy.

I achieved that by editing "docker-compse.yml":
`    ports:
      - "25:25"
      - "127.0.0.1:8000:8000"
`
For some reason the "mode: host" option did not working to support the long variant of the port description you chose.
Anyway, there should be an config option available to set the binding ip address without the need to edit the compose yml.

Cheers.

**Comment by crazy-max** [comment]
@Flunkyball `network_mode: host` is not compatible with this image. It's also not recommended because that container’s network stack is not isolated from the Docker host (the container shares the host’s networking namespace), and the container does not get its own IP-address allocated. If you really want that you can fork this repo and make your own changes.
