### ISSUE TITLE
[Enhancement] Add support scripts for starting/stopping as well as a systemd service

### ISSUE THREAD

**Issue by Flunkyball** [anonaddy/docker#37]
I recently set up an searx-docker instance and they deliver some simple but useful scripts to start/stop the compose process as well as setting up a systemd service for that.
Since the whole thing is mostly generic I thought it would be a nice idea to add it to this project as well.

Start: https://github.com/searx/searx-docker/blob/master/start.sh
Stop: https://github.com/searx/searx-docker/blob/master/stop.sh
Utility: https://github.com/searx/searx-docker/blob/master/util.sh
Service Template: https://github.com/searx/searx-docker/blob/master/searx-docker.service.template

Cheers.

**Comment by crazy-max** [comment]
@Flunkyball It's not something we intend to support/endorse because it's outside the scope of this repo which only provides an image for AnonAddy and not a whole ecosystem to manipulate it (apart from core components like docker or docker-compose, swarm or k8s deployments). But thanks for this suggestion, I'm sure it will help others!
